FROM mcr.microsoft.com/dotnet/sdk:7.0.406 as build
WORKDIR /app
EXPOSE 80

# copy all .csproj files and restore as distinct layers. use of the same COPY command
# for every dockerfile in the project to take advantage of docker caching
COPY Carsties.sln Carsties.sln
COPY src/AuctionService/AuctionService.csproj src/AuctionService/AuctionService.csproj
COPY src/SearchService/SearchService.csproj src/SearchService/SearchService.csproj
COPY src/GatewayService/GatewayService.csproj src/GatewayService/GatewayService.csproj
COPY src/IdentityService/IdentityService.csproj src/IdentityService/IdentityService.csproj
COPY src/Contracts/Contracts.csproj src/Contracts/Contracts.csproj

# restore package dependencies
RUN dotnet restore Carsties.sln

# Copy the app folder over
COPY src/SearchService src/SearchService
COPY src/Contracts src/Contracts
WORKDIR /app/src/SearchService
RUN dotnet publish -c release -o /app/src/out

# build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0.16
WORKDIR /app
COPY --from=build /app/src/out .
ENTRYPOINT [ "dotnet","SearchService.dll" ]
